# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  CppTemplatePremake_config = debug

else ifeq ($(config),release)
  CppTemplatePremake_config = release

else ifeq ($(config),distribute)
  CppTemplatePremake_config = distribute

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := CppTemplatePremake

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CppTemplatePremake:
ifneq (,$(CppTemplatePremake_config))
	@echo "==== Building CppTemplatePremake ($(CppTemplatePremake_config)) ===="
	@${MAKE} --no-print-directory -C CppTemplatePremake -f Makefile config=$(CppTemplatePremake_config)
endif

clean:
	@${MAKE} --no-print-directory -C CppTemplatePremake -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  distribute"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CppTemplatePremake"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"